var living_classroom =
[
  {
    "ID":"living_classroom_1",
    "School State":"WY",
    "School City":"Pinedale",
    "Institution":"Pinedale High School",
    "Living classroom State":"WY\n\n\n",
    "Living Classroom Water Body":"Green River",
    "x":38.16691,
    "y":-109.75966,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Canyonlands_National_Park&params=38.16691_N_109.75966_W_type:landmark_",
    "Living Classroom Description":"Headwaters of the Green & Colorado Rivers",
    "Administrators & Teachers":"Ben Smith, Principal",
    "Teacher":"Deb Noble, Science Teacher",
    "Demographics":"~60 students, mid. Class (80% Cauc., 10% Latino)\n"
  },
  {
    "ID":"living_classroom_2",
    "School State":"CO",
    "School City":"Glenwood Springs",
    "Institution":"Yampah High School",
    "Living classroom State":"CO\n  \n",
    "Living Classroom Water Body":"Colorado River",
    "x":39.55,
    "y":-107.316667,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Glenwood_Springs%2C_Colorado&params=39_33_N_107_19_W_region:US_type:city",
    "Living Classroom Description":"Glenwood Springs",
    "Administrators & Teachers":"Leigh McGowan, Principal\n",
    "Teacher":"Susy Ellison, Science Teacher",
    "Demographics":"  ~20 students\n  40% Latino\n"
  },
  {
    "ID":"living_classroom_3",
    "School State":"CO",
    "School City":"Telluride",
    "Institution":"Telluride High School",
    "Living classroom State":"CO\n",
    "Living Classroom Water Body":"San Miguel River",
    "x":37.926944,
    "y":-107.775833,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=San_Miguel_River_%28Colorado%29&params=37_55_37_N_107_46_33_W_",
    "Living Classroom Description":"(tributary of the Colorado River via Dolores River.)",
    "Administrators & Teachers":"Mike Conran,\nPrincipal",
    "Teacher":"Rex Lybrand, Science Teacher",
    "Demographics":"~60\nstudents, Upper\nmid. Class (93% Cauc., 6.5% Lat.)"
  },
  {
    "ID":"living_classroom_4",
    "School State":"CO",
    "School City":"Nucla/Naturita",
    "Institution":"Nucla High\nSchool\n",
    "Living classroom State":"CO ",
    "Living Classroom Water Body":"Dolores River",
    "x":38.816667,
    "y":-109.267222,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Dolores_River&params=38_49_00_N_109_16_02_W_type:river_region:US-CO",
    "Living Classroom Description":"Bedrock (tributary of the Colorado\nRiver)",
    "Administrators & Teachers":"Tom Taucher, Principal",
    "Teacher":"Christine Harty, Science Teacher",
    "Demographics":"~60 students, Working class, (92% Cauc., 3.5% Latino, 3.5% Nat. Am.)\n"
  },
  {
    "ID":"living_classroom_5",
    "School State":"CO",
    "School City":"Grand Junction",
    "Institution":"Grand Junction High School",
    "Living classroom State":"CO",
    "Living Classroom Water Body":"Colorado River",
    "x":39.066667,
    "y":-108.566667,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Grand_Junction%2C_Colorado&params=39_04_N_108_34_W_region:US_type:city",
    "Living Classroom Description":"Colorado River at Grand Junction",
    "Administrators & Teachers":"Jon Bilbo, Principal",
    "Teacher":"Kristen McClellen, Science Teacher",
    "Demographics":"~60 students, Working class,\n(89% Cauc., 11% Latino & Nat. Am.)"
  },
  {
    "ID":"living_classroom_6",
    "School State":"UT",
    "School City":"Moab",
    "Institution":"Grand County High School",
    "Living classroom State":"UT",
    "Living Classroom Water Body":"Colorado River",
    "x":38.5725,
    "y":-109.549722,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Moab%2C_Utah&params=38_34_21_N_109_32_59_W_region:US_type:city",
    "Living Classroom Description":"Colorado River at Moab",
    "Administrators & Teachers":"Stephen Hren, Principal\n",
    "Teacher":"Laura Reed, Science Teacher; Mary Walker-Irvin, Science",
    "Demographics":"~30 Students. Working class. (5% Latino; 5% Nat. Am.)\n"
  },
  {
    "ID":"living_classroom_7",
    "School State":"AZ",
    "School City":"Tsaile",
    "Institution":"Diné College",
    "Living classroom State":"AZ\n",
    "Living Classroom Water Body":"San Juan River",
    "x":37.179722,
    "y":-110.900833,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=San_Juan_River_%28Colorado_River%29&params=37_10_47_N_110_54_03_W_type:river_region:US-NM",
    "Living Classroom Description":"(tributary of\nColo. R. near Chinle,\nAZ)",
    "Administrators & Teachers":"Henry Fowler, Professor\n",
    "Teacher":"Corvina Etsitty, Science Teacher",
    "Demographics":"Nat. Am. community group (99% +\nNat. Am.,) 1% Other)"
  },
  {
    "ID":"living_classroom_8",
    "School State":"NV",
    "School City":"Boulder City",
    "Institution":"Boulder City High School",
    "Living classroom State":"NV",
    "Living Classroom Water Body":"Lake Mead",
    "x":36.25,
    "y":-114.39,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Lake_Mead&params=36.25_N_114.39_W_region:US_type:waterbody_scale:500000",
    "Living Classroom Description":"(Colorado River\nabove Boulder City, NV).",
    "Administrators & Teachers":"Kent Roberts, Principal",
    "Teacher":"Chris Bires, Science Teacher",
    "Demographics":"~60 stud.,Mid. class (81% Cauc.,11% Lat., 7.5% other)"
  },
  {
    "ID":"living_classroom_9",
    "School State":"AZ",
    "School City":"Lake Havasu City",
    "Institution":"Lake Havasu City High School",
    "Living classroom State":"AZ\n",
    "Living Classroom Water Body":"Lake Havasu",
    "x":34.483333,
    "y":-114.383333,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Lake_Havasu&params=34_29_N_114_23_W_region:US_type:waterbody",
    "Living Classroom Description":"(main stem Colo.River)",
    "Administrators & Teachers":"Denise Miner, Principal",
    "Teacher":"Nancy Schweigert, Science Teacher",
    "Demographics":"~60 stud.,Mid. class (81% Cauc.,11% Lat. 7.5%)"
  },
  {
    "ID":"living_classroom_10",
    "School State":"AZ",
    "School City":"Yuma",
    "Institution":"Yuma High School\n",
    "Living classroom State":"AZ\n",
    "Living Classroom Water Body":"Colorado River",
    "x":32.692222,
    "y":-114.615278,
    "GeoHack":"http://tools.wmflabs.org/geohack/geohack.php?pagename=Yuma%2C_Arizona&params=32_41_32_N_114_36_55_W_region:US_type:city",
    "Living Classroom Description":"Colorado River at Yuma",
    "Administrators & Teachers":"Faith Klostreich, Principal\n",
    "Teacher":"Filomeno Munoz, AP Science Teacher",
    "Demographics":"~120, Title I, Working class (81% Latino)\n"
  }
]

          
